name: Pre-Commit
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses:
        enabl-tech/ros2_control_ci/.github/workflows/reusable-pre-commit.yml@master
    with:
      ros_distro: jazzy
